### PR TITLE
added questions and correct answers

### PR DESCRIPTION
**Pull request by Asieger75**

### CODE REVIEW

**Comment by jboe26** [comment]
nice

**Comment by Asieger75** [comment]
fixed, if someone wants to review/approve

**Comment by jboe26** [comment]
ill do it when im back

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CeaserSP** [comment]
What is going on here?

**Comment by jboe26** [comment]
this is what william was working on, this isnt my pull request for the routes

**Pull request closed without merging**
